server {
    listen 80;
    server_name _;

    # 1. 统一匹配静态页面
    location /ha-project/admin/ {
        alias /usr/share/nginx/html/;
        index index.html index.htm;
        try_files $uri $uri/ /ha-project/admin/index.html;
    }

    # 2. 统一匹配图片资源
    location /ha-project/admin/uploads/ {
        alias /usr/share/nginx/html/uploads/;
        expires 7d;
    }

    # 3. 统一匹配后端 API 接口
    location /ha-project/admin/api/ {
        # 🌟 关键：转发给 Koa 时抹去 /ha-project/admin/ 前缀，保留 /api/ 给 Koa 的 JWT 校验
        proxy_pass http://app:8001/api/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}